server:
  port: 8085
slack:
  token: YOUR_TOKEN_HERE
  username: phabulous
conduit:
  user: etcinit
  api: ''
  cert: ''
channels:
  feed: '#phabricator'
  repositories:
    CALLSIGN: channel
    OTHERCALLSIGN: otherchannel
  projects:
    10: anotherchannel
misc:
  ignore-ca: false
