server:
  # Which hostname to listen for incoming connections.
  #
  # Examples:
  #
  # To listen on local connections over IPv6 only:
  # - '[::1]'
  #
  # To listen on local connections over IPv4 only:
  # - '127.0.0.1'
  #
  # To listen to the IP addresses a domain resolves to:
  # - some.domain.net
  hostname: ''
  port: 8085

  debug: false

  # Serious-mode makes some messages more formal and business-friendly.
  serious: false
slack:
  token: YOUR_TOKEN_HERE
  username: phabulous
conduit:
  api: https://phabricator.replace.me

  # For token-based auth, use the following key:
  token: YOUR_TOKEN_HERE

  # For certificate-based auth, use the following keys:
  #user: etcinit
  #cert: ''
channels:
  # The feed channel is where Phabulous will post every feed event to this
  # channel. Leave it blank to disable this feature.
  feed: '#phabricator'

  # You can map repositories to a channel. This will send feed events regarding
  # commits and revisions to the specified channel.
  repositories:
    CALLSIGN: '#channel'
    OTHERCALLSIGN: '#otherchannel'

  # You can map projects to a channel. This will send feed events regarding
  # tasks to the specified channel.
  projects:
    10: '#anotherchannel'
misc:
  ignore-ca: false
